[versions]
kimchi = "2.0.3"
watermelon = "1.0.1"
regolith = "0.5.0"

[libraries.kimchi-core]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:core"

[libraries.kimchi-logger]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:logger"

[libraries.spondee]
version = "1.3.0"
module = "com.inkapplications.spondee:units"

[libraries.watermelon-coroutines]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:coroutines"

[libraries.watermelon-standard]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:standard"

[libraries.regolith-processes]
version.ref = "regolith"
module = "com.inkapplications.regolith:processes"

[bundles]
watermelon-kotlin = [
    "watermelon-coroutines",
    "watermelon-standard",
]
