[versions]
kotlin = "2.0.0"
coroutines = "1.8.1"

[libraries.gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.test-junit]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-junit"

[libraries.coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.coroutines-test]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"

[libraries.coroutines-js]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js"

[libraries.datetime]
version = "0.6.0"
module = "org.jetbrains.kotlinx:kotlinx-datetime"

[libraries.serialization-json]
version = "1.7.0"
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"

[libraries.serialization-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-serialization"
