[versions]
ktor = "2.2.1"

[libraries.client-core]
version.ref = "ktor"
module="io.ktor:ktor-client-core"

[libraries.serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.client-serialization]
version.ref = "ktor"
module="io.ktor:ktor-client-serialization"

[libraries.client-okhttp]
version.ref = "ktor"
module="io.ktor:ktor-client-okhttp"

[libraries.client-cio]
version.ref = "ktor"
module="io.ktor:ktor-client-cio"

[libraries.client-js-core]
version.ref = "ktor"
module="io.ktor:ktor-client-js"

[libraries.client-js-json]
version.ref = "ktor"
module="io.ktor:ktor-client-json-js"

[libraries.server-netty]
version.ref = "ktor"
module="io.ktor:ktor-server-netty"

[libraries.server-websockets]
version.ref = "ktor"
module="io.ktor:ktor-server-websockets"

[libraries.client-websockets]
version.ref = "ktor"
module="io.ktor:ktor-client-websockets"

[libraries.client-contentnegotiation]
version.ref = "ktor"
module="io.ktor:ktor-client-content-negotiation"
