[versions]
sqldelight = "1.5.5"

[libraries.sqldelight-gradle]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:gradle-plugin"

[libraries.sqldelight-driver]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:sqlite-driver"

[libraries.sqldelight-coroutines]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:coroutines-extensions"

[libraries.junit]
version = "4.12"
module = "junit:junit"

[bundles]
sqldelight = ["sqldelight-driver", "sqldelight-coroutines"]
