on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v2.3.4
            -
                name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: adopt
                    java-version: '15'
            -
                name: Checks
                run: bin/gradlew check
