name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4.2.2
            -
                name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: adopt
                    java-version: 21
            -
                name: JVM Tests
                run: bin/gradlew jvmTest
            -
                name: Build
                run: bin/gradlew build
