name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v2.3.4
            -
                name: JVM Tests
                run: ./gradlew jvmTest
            -
                name: Build
                run: ./gradlew build
